#!/usr/bin/env python3

import os, sys

count = 0
for line in sys.stdin:
    olinev = line.strip().split()
    nlinev = []
    for wd in olinev:
        try:
            uwd = bytearray(wd, 'utf8', errors='ignore').decode('utf8', errors='ignore')
            nlinev.append(uwd)
        except:
            count += 1
            pass
    oline = ' '.join(olinev)
    nline = ' '.join(nlinev)
    if oline != nline:
       sys.stderr.write('badline:: %s\n' % oline)
    print(nline)
if count > 0:
    sys.stderr.write('Total bad words skipped: %d\n' % count)
