#!/usr/bin/env python3

import os, sys, io

count = 0
try:
    stdin = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8', errors='ignore')
    stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='ignore')
    for line in stdin:
        count += 1
        stdout.write(line.strip())
        stdout.write('\n')
except:
    sys.stderr.write(f'Error while procrssing line: {count}')
    raise
