#!/usr/bin/env python2

import os, sys

while True:
    line = sys.stdin.readline()
    if line == '':
        break
    olinev = line.strip().split()
    nlinev = []
    for wd in olinev:
        try:
            uwd = wd.decode('utf8').encode('utf8')
            nlinev.append(uwd)
        except:
            pass
    oline = ' '.join(olinev)
    nline = ' '.join(nlinev)
    if oline != nline:
       sys.stderr.write('badline %s\n' % oline)
    sys.stdout.write(nline + '\n')
    sys.stdout.flush()
